name: Build

on:
    push:
        branches:
            - main
permissions:
    id-token: "write"
    contents: "write"
    packages: "write"
    pull-requests: "read"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: "temurin"
            - name: Build with Gradle
              run: ./gradlew build '-Pversion=${{ github.run_number }}'
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: SmpConnect
                  path: ./build/libs/smpconnect*.jar
            - name: Publish Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "v${{ github.run_number }}-alpha"
                  prerelease: true
                  files: |
                      LICENSE
                      ./build/libs/smpconnect-${{ github.run_number }}.jar
